### ISSUE TITLE
Feature request: properly handle cancellation of `selector` command

### ISSUE THREAD

**Issue by nazarewk** [Anomalocaridid/handlr-regex#23]
Could you possibly take a look at my use case (pressing `esc` in `wofi` to cancel opening the link instead of falling through to system apps)? Sadly I don't understand enough Rust to implement/fix it myself.

https://github.com/chmln/handlr/issues/72

**Comment by Anomalocaridid** [comment]
I can replicate the bug on my end. It seems pretty straightforward and it shouldn't take me too long to come up with a fix. Thanks for pointing me in the right direction btw.

**Comment by Anomalocaridid** [comment]
I think it's fixed. Would you mind cloning and running the handle-selector-cancellation branch to make sure it works on your end?

**Comment by Anomalocaridid** [comment]
@nazarewk Would you please try running the handle-selecrion-cancellation branch on your system to double-check the fix works before I merge it?

**Comment by nazarewk** [comment]
will look into it today

**Comment by nazarewk** [comment]
doesn't look like it changed anything when switching versions in my configs, but can look further into it tomorrow https://github.com/nazarewk-iac/nix-configs/commit/6fc060d1

**Comment by Anomalocaridid** [comment]
You could probably just clone the repo, switch to the handle-selector-cancellation branch , install the Rust toolchain, maybe in a `nix-shell`, and try to open an https link with `cargo run -- open <link>`. It'll just compile and run the code without installing anything.

I just need you to do a quick check to ensure it works. I'm going to merge this fix, and create a new release as soon as we confirm it works anyways.

**Comment by nazarewk** [comment]
I've never developed in Rust don't have much idea about running it under NixOS, but I managed to build (so far my own) package to compile your version at https://github.com/nazarewk-iac/nix-configs/commit/2a9040ee

It indeed has fixed the lack of cancellation, looks like I pasted the wrong commit before.

**Comment by Anomalocaridid** [comment]
Great! Thanks for reporting this!
