### ISSUE TITLE
Re: Terminal=true

### ISSUE THREAD

**Issue by ld991** [Anomalocaridid/handlr-regex#33]
When opening text files from outside the terminal  (through `dmenu` or `lf`, for example) along with properly opening the file, it also opens up another terminal that says:

```
ERROR


Unknown URL type, cannot open:
  %U
  -e
  nvim
 
```

**Comment by ld991** [comment]
Sorry, I should have properly read the README. I found a section that talks about x-scheme-handler, and now the issue is fixed. I don't remember what it was initially set to, but I changed it and now it works excellently.

I was personally expecting it to read the environment variable called 'TERMINAL'.

**Comment by Anomalocaridid** [comment]
It's all good. I know I do the exact same thing on occasion.
