### ISSUE TITLE
How do u even use the regex?

### ISSUE THREAD

**Issue by sbeve72** [Anomalocaridid/handlr-regex#35]
I was using Mimeo until now but lack of auto-completion made me try this instead but the problem is, now neither Mimeo nor the regex support with Handlr-Regex work.

```
$ handlr get glob:text/*
error: Invalid value "glob:text/*" for '<MIME>': mime parse error: an invalid token was encountered, 3A at position 4

For more information try --help
```

**Comment by sbeve72** [comment]
`$ handlr set "image/*" org.gnome.Loupe.desktop ` adds a literal "image/*" to mimeapps.list tho.

**Comment by Anomalocaridid** [comment]
My bad. I guess I was mistaken. Please disregard what I said about putting it in quotes.

**Comment by sbeve72** [comment]
Removing the quotes (") doesn't work either
`$ handlr set image/* org.gnome.Loupe.desktop`

**Comment by Anomalocaridid** [comment]
That's how it's supposed to work. It's not like `mimeo` where it expands to every matched possibility in mimeapps.list.

**Comment by Anomalocaridid** [comment]
@sbeve72 Are you still having trouble using `handlr` or can this issue be closed?

**Comment by sbeve72** [comment]
Yes
