### ISSUE TITLE
How do I backup the associations?

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [Anomalocaridid/handlr-regex#42]
Title. Can we define associations in the config file? What if you set up a bunch of associations and then had to switch computers or something?

**Comment by Anomalocaridid** [comment]
`handlr` reads and writes associations to and from `~/.config/mimeapps.list`. So just copy this file to your new computer.

Also, it's the same file that other openers like `xdg-open` and `mimeo` use, although if you use `handlr`-specific features like wildcards in `mimeapps.list`, it might not work with other file openers without making changes.

**Comment by limaceous-bushwhacker** [comment]
Hi, thanks for the quick reply. I'm wondering what's the difference between the two `mimeapps.list`? (The other one being in `~/.local/share/applications/mimeapps.list`)

**Comment by Anomalocaridid** [comment]
Happy to help!
