### ISSUE TITLE
`--json` for `handlr list`

### ISSUE THREAD

**Issue by nazarewk** [Anomalocaridid/handlr-regex#46]
It would be useful to have a `--json` switch for `handlr list` command, just like on `get` and `mime`.

Current (tabular) output is so stripped down to fit columns it's not very useful.

**Comment by Anomalocaridid** [comment]
I agree, it would be useful. I'll add it when I have the time.

I'll also see what I can do about the table output.

**Comment by nazarewk** [comment]
Table output could fit the terminal size, it seems to have a constant width no matter the terminal size right now.

**Comment by Anomalocaridid** [comment]
Sorry for forgetting about this for like a month. `handlr list` now has support for `--json`. I also made the tabular output a bit more useful.
