### ISSUE TITLE
Update documentation regarding usage in place of xdg-open

### ISSUE THREAD

**Issue by nut-3** [Anomalocaridid/handlr-regex#53]
Hello.
First, thanks for the project, it's awesome! )
Second. I think documentation part that covers usage handlr instead of xdg-open on Arch should be altered little bit.
`xdg-utils-handlr` aur package is not actively maintained. Right now it depends on handlr-regex (this was not the case yesterday), but in forces removal of xdg-utils. So it can cause compatibility issues with other applications because of not having `xdg-desktop-icon` and other scripts on their system.
Maybe consider changing documentation so that it advertises "shadowing" xdg-open in a user-scoped location in a $PATH, such as ~/.local/bin? Last comment from a former `xdg-utils-handlr` maintener suggests [doing the same](https://aur.archlinux.org/packages/xdg-utils-handlr#comment-927741).

**Comment by Anomalocaridid** [comment]
Sorry for ignoring this issue for a few weeks. I want to let you know I have seen this and I intend to update the documentation about this eventually.
