### ISSUE TITLE
add cmd-line argument for 'enable_selector'

### ISSUE THREAD

**Issue by superiums** [Anomalocaridid/handlr-regex#60]
enable_selector  now could only be defined in config, but how if we both need enable and disable? i use it with `lf`, sometimes i need to enable select, and sometimes not.

also hope to add an argument to read the selector from cmdline. instead of config file. in this way, it's more flexiable to use diffenrent selector for different enviroment.

**Comment by Anomalocaridid** [comment]
That's a good idea.

Just so I can understand your request a bit better, could you tell me a bit more your particular use case? Like in what situations do you want a selector and in what situations do you not want one? Also what environments are you referring to that would require using different selectors?

Also how are you using `handlr` with `lf`? I have never used `lf`, so I am not familiar with it.

**Comment by superiums** [comment]
`lf` is a pretty file manager with TUI , it's the most flexiable one , also similar ones are: `ranger`, `nnn`, `jushuto`, `yazi`, `felix` ....

my use case:

- open with selection
  this works like 'open with' menu in GUI file manager. you have more choice , for example, a video, you may choose shotcut/olive/.... any tool to edit it. or different browser to open  html file for some purpose.

- open without selection
this works like double click to open in GUI file manager. it's fast and no need to choose. just use default one in mime.

- with different selector
in `lf` or other TUI , i prefer to use `fzf` to choose.

in `spacefm` , `thunar` or other GUI, i prefer to use `wofi` or `fuzzel` to choose.

**Comment by Anomalocaridid** [comment]
Command-line flags to enable/disable the selector and override the selector command have been added.

There's still a handful of things I have planned before I make a new release, so it'll be a bit longer.
