### ISSUE TITLE
Wildcards do not appear to work with GUI file managers

### ISSUE THREAD

**Issue by uwidev** [Anomalocaridid/handlr-regex#75]
I'm having some issues getting files to open properly using GUI file managers. They do not open files with the correct program.

Tested GUI file managers:
- `pcmanfm-qt`
- `thunar`

Here's my barebones `mimeapps.list`
```ini
[Default Applications]
image/*=org.nomacs.ImageLounge.desktop;
text/*=nvim.desktop;
```

I have tried touching `handlr.toml`, however I was not able to get anything to work. I gave up messing with it and am just using defaults.
```ini
enable_selector = false
selector = "rofi -dmenu -i -p 'Open With: '"
term_exec_args = '-e'
```
I tried to add `nomacs` as my default image viewer on `handlr.toml` as follows, but it isn't recognized when running `handlr get image/png`. _This is when unsetting the `image/*` assignment under mimeapps.list._ So I'm not too sure if this is the problem, as I followed a similar formatting to the readme.
```ini
[[handlers]]
exec = "nomacs %f"
terminal = false
regexes = ['image/.+']
```

For reference, this is what the .desktop for nomacs is.
```ini
[Desktop Entry]
Name=nomacs
GenericName=Image Viewer
Comment=nomacs is a free, open source image viewer.
Exec=nomacs %f
Terminal=false
Icon=org.nomacs.ImageLounge
Type=Application
Categories=Graphics;RasterGraphics;Viewer;2DGraphics;
MimeType=image/avif;image/bmp;image/gif;image/heic;image/heif;image/jpeg;image/jxl;image/png;image/tiff;image/webp;image/x-eps;image/x-ico;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-xbitmap;image/x-xpixmap;
GenericName[de]=Bildbetrachter
Comment[de]=Ressourcenschonender, plattformübergreifender Bildbetrachter mit Unterstützung für verschiedenste Formate
Name[pt]=nomacs
GenericName[pt]=Visualizador de imagens
Comment[pt]=Um visualizador de imagens desenvolvido em Qt
```

Running `xdg-mime` with debug `image/png` yields the following.
```sh
> env XDG_UTILS_DEBUG_LEVEL=2 xdg-mime query default image/png
Checking /home/timmy/.config/mimeapps.list
Checking /home/timmy/.local/share/applications/mimeapps.list
Checking /home/timmy/.local/share/applications/defaults.list and /home/timmy/.local/share/applications/mimeinfo.cache
Checking /home/timmy/.local/share/applications/defaults.list and /home/timmy/.local/share/applications/mimeinfo.cache
Checking /home/timmy/.local/share/flatpak/exports/share/applications/defaults.list and /home/timmy/.local/share/flatpak/exports/share/applications/mimeinfo.cache
Checking /home/timmy/.local/share/flatpak/exports/share/applications/defaults.list and /home/timmy/.local/share/flatpak/exports/share/applications/mimeinfo.cache
Checking /var/lib/flatpak/exports/share/applications/defaults.list and /var/lib/flatpak/exports/share/applications/mimeinfo.cache
Checking /var/lib/flatpak/exports/share/applications/defaults.list and /var/lib/flatpak/exports/share/applications/mimeinfo.cache
Checking /usr/local/share//applications/defaults.list and /usr/local/share//applications/mimeinfo.cache
Checking /usr/local/share//applications/defaults.list and /usr/local/share//applications/mimeinfo.cache
Checking /usr/share//applications/defaults.list and /usr/share//applications/mimeinfo.cache
chromium.desktop
```

Running `handlr get image/png` yields what I expect: `org.nomacs.ImageLounge.desktop`.

**I have xdg-open shadowed as seen in the readme.**
```sh
> xdg-open
error: the following required arguments were not provided:
  <PATHS>...

Usage: handlr open <PATHS>...

For more information, try '--help'.
```
Using a TUI file manager like `yazi` has the file open correctly. I have only tested `yazi`.

No, I do not have any other `*-mimeapps.list` files under `~/.config`.

I **have** gotten this to work when I use `image/png`. It will work on my GUI file explorers, and when using built-in `xdg-open`. However, this does seem to defeat the purpose of handlr-regex and wildcard support.

I don't know what I'm doing wrong or if it just straight up isn't supported for GUI file handlers. Any help in troubleshooting this, etc., would be appreciated.

**Comment by uwidev** [comment]
That's what I was speculating, darn. Because the only way it wouldn't work is if it straight up did not use `xdg-open`, or directly referenced the binary on the system rather than looking up `$PATH`.

Do you have any recommendations on what does work? Perhaps we could have a small documentation of known GUI file managers that utilize `xdg-open`? Or maybe I'm not looking at the right places on the arch wiki.

**Comment by Anomalocaridid** [comment]
> Do you have any recommendations on what does work?

Unfortunately, I do not. It has been years since I last regularly used a GUI file manager.

I know `nnn`, `yazi`, `xplr`, `superfile`, and possibly `ranger` use `xdg-open` at least as a fallback, but those are all TUI file managers.

> Perhaps we could have a small documentation of known GUI file managers that utilize xdg-open?

That's a good idea. I'd be up for documenting that as soon I know of any examples. I'm sure there's got to be some program that fits that description.

> Or maybe I'm not looking at the right places on the arch wiki.

I haven't been able to find much information there regarding GUI file managers that use `xdg-open.` Unfortunately, I haven't had much luck elsewhere either.

**Comment by uwidev** [comment]
I see. I needed a way to manage pictures, hence my usage of thumbnails in GUI file managers. I wonder if there's a TUI that can display like a grid of images but still as TUI. That's something I guess I'd have to do research on my own.

But that said, as a workaround, earlier I mentioned that using `image/gif` works as expected. What are your thoughts on having `image/*` insert all known mime types of `image/` into `mimeapps.list`? I could see it as potentially troublesome to manage, however.

**Comment by Anomalocaridid** [comment]
> I see. I needed a way to manage pictures, hence my usage of thumbnails in GUI file managers. I wonder if there's a TUI that can display like a grid of images but still as TUI. That's something I guess I'd have to do research on my own.

I know `nnn` has something like that with its [`imgview`](https://github.com/jarun/nnn/wiki/Basic-use-cases#image-video-pdf) plugin.

You probably already know this, but other TUI file managers like `yazi`, `xplr`, and I think maybe `ranger` support image previews, but only for the currently selected file.

> But that said, as a workaround, earlier I mentioned that using image/gif works as expected. What are your thoughts on having image/* insert all known mime types of image/ into mimeapps.list? I could see it as potentially troublesome to manage, however.

I might consider adding an option that enables that behaviour, but I can't promise I'll be able to get around to implementing it anytime soon.

You might want to check out [mimeo](https://xyne.dev/projects/mimeo/). It works that way and it even has a feature that's similar to `handlr-regex`'s regex handlers. In fact, it inspired this fork.

**Comment by uwidev** [comment]
Thank you. I will take a look at mimeo, but I'll take a look around at handlr's code when I get the chance to see how feasible it would be to do something like that. I really like handlr's user logic and would like to continue using it.

**Comment by Anomalocaridid** [comment]
I have added an option to expand wildcards for next release. See README.md for more information.
