### ISSUE TITLE
Carriage return in ~/.config/mimeapps.list

### ISSUE THREAD

**Issue by hashworks** [Anomalocaridid/handlr-regex#78]
After using `handlr-regex` my `.config/mimeapps.list` is using `\r\n`:

`git diff .config/mimeapps.list`
```diff
-[Added Associations]
[...]
+[Added Associations]^M
```

I don't think this breaks anything, it's just unusual. `handlr-regex` should use a single newline instead.

**Comment by Anomalocaridid** [comment]
Agreed. I already intend to try to fix this before the next release.
