### ISSUE TITLE
Base mime on file extension not on contents (chmln#70)

### ISSUE THREAD

**Issue by JacobTravers** [Anomalocaridid/handlr-regex#8]
Copy of https://github.com/chmln/handlr/issues/70
> Right now, the crate uses the contents of the file to determine mime, similar to the command `file`. However, it should base it on solely the file extension, like `xdg-*`.
> 
> Right now, if you make an empty file, eg. `touch test.txt`, then try `handlr open test.txt`, it will fail with `no handlers found for 'application/x-zerosize'`.

**Comment by Anomalocaridid** [comment]
I can replicate this on my end.

I disagree that `handlr` should solely use the file extension to determine mimetype, but I agree that the file extension should take precedence.  Using file contents should still be a fallback for when the file extension is ambiguous.

If you think it would be worthwhile, I could try to implement a config option that completely ignores file contents.

Also, while I'm working on a fix for this, you might want to consider using the [regex handler](https://github.com/Anomalocaridid/handlr-regex#setting-regex-handlers) feature as a temporary workaround if you aren't already.

Just in case you aren't, this snippet might help. Just replace `EDITOR` with whatever program you use for .txt files and delete `terminal = true` if it's a GUI program.
```toml
[[handlers]]
exec = "EDITOR %f"
terminal = true
regexes = ['.*\.txt']
```

**Comment by Anomalocaridid** [comment]
I think I fixed it. Would you mind downloading and running the fix-file-extension-not-contents branch to confirm it works on your system?

**Comment by JacobTravers** [comment]
Yes this works for me as well! 👍🏽

**Comment by Anomalocaridid** [comment]
Great! Thanks for reporting this!
